---
- name: Deploy Amadeus Flight API to AWS
  hosts: amadeus_servers
  become: no # We don't need sudo anymore because we added 'ubuntu' to the docker group!

  tasks:
    - name: 1. Create an application folder on the server
      file:
        path: /home/ubuntu/amadeus-app
        state: directory

    - name: 2. Securely copy our code from the laptop to AWS
      copy:
        src: ../{{ item }} # Tells Ansible to look one folder up (in amadeus-poc)
        dest: /home/ubuntu/amadeus-app/
      loop:
        - app.py
        - requirements.txt
        - Dockerfile
        - docker-compose.yml

    - name: 3. Build the Docker Image physically on the AWS server
      command: docker build -t flight-api:v1 .
      args:
        chdir: /home/ubuntu/amadeus-app # Tells Ansible to run the command inside this folder

    - name: 4. Launch the Microservices via Docker Compose
      command: docker compose up -d
      args:
        chdir: /home/ubuntu/amadeus-app