# We group our servers under a label called [amadeus_servers]
[amadeus_servers]
13.38.217.70

# We tell Ansible exactly how to connect to any server in this group
[amadeus_servers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/amadeus_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'